// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookInput struct {
	Title     string `json:"title"`
	Author    string `json:"author"`
	Publisher string `json:"publisher"`
	CountryID int    `json:"countryId"`
}

type CountryInput struct {
	Name string `json:"name"`
}
